spring.datasource.url=jdbc:postgresql://localhost:5432/book_bd
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.metadata_builder_contributor=de.ait.gr5.bs.utils.SqlFunctionsMetadataBuilderContributor

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc.datasource.init=DEBUG

API_URL_FOUND_CITY=https://app.zipcodebase.com/api/v1/search
API_KEY_ZIPCODEBASE=2e449070-5124-11f1-9505-93eae7106900
