INSERT INTO CATEGORIES (TITLE) VALUES ('Esse');
INSERT INTO CATEGORIES (TITLE) VALUES ('Roman');
INSERT INTO CATEGORIES (TITLE) VALUES ('Detektiv');
INSERT INTO CATEGORIES (TITLE) VALUES ('Fantasy');

insert into countries (title) values (Germany);
