### Add new book

POST localhost:8080/api/books
Content-Type: application/json

{
 "title": "2",
 "author": "22Robin Wall Kimmerer",
 "description": "life as an indigenous how other living beings...",
 "categoryId": 1,
 "language": "English",
 "pages": 108,
 "publisherDate": "2015-04-11",
 "cover": "f:/book_db/1.jpg",
 "owner": 1
}

### Update information of the book

PUT localhost:8080/api/books/1
Content-Type: application/json

{
  "title": "Braiding Sweetgrass",
  "author": "Robin Wall Kimmerer",
  "description": "Drawing on her life as an indigenous scientist, and as a woman, Kimmerer shows how other living beings...",
  "categoryId": 1,
  "language": "English",
  "pages": 4008,
  "publisherDate": "2015-04-11",
  "cover": "f:/book_db/1.jpg",
  "owner": 1
}

### Get all books without filter
GET localhost:8080/api/books/
Content-Type: application/json

### Get all books with filter - user_id
GET localhost:8080/api/books/?userId=1
Content-Type: application/json

### Get all books with filter - multiSearch
GET localhost:8080/api/books/?multiSearch=Детектив WalL title
Content-Type: application/json


### Get all books with filter - categoryId
GET localhost:8080/api/books/?categoryId=1
Content-Type: application/json

### Get all books with filter - language
GET localhost:8080/api/books/?language=English&userId=1&multiSearch=kimmerer
Content-Type: application/json

### Get all books with filter - language
GET localhost:8080/api/books/?language=English
Content-Type: application/json

### Get all books with filter -location
GET localhost:8080/api/books/?location=Berlin
Content-Type: application/json

### Get delail of book
GET localhost:8080/api/books/1/detail
Content-Type: application/json

### Add book to user
POST localhost:8080/api/books/getting
Content-Type: application/json

{
 "bookId": 1,
 "userId": 4
}

### Get my history
GET localhost:8080/api/books/history/2
Content-Type: application/json

### Get my waiting list
GET localhost:8080/api/books/waiting/4
Content-Type: application/json

### Get filter
GET localhost:8080/api/books/filter
Content-Type: application/json

