### Add new book

POST localhost:8080/api/books
Content-Type: application/json

{
  "title": "English Grammar in Use. Book with Answers",
  "author": "Murphy Raymond",
  "description": "This book has clear explanations and practice exercises that have helped millions of people around the world improve their English",
  "categoryId": 2,
  "languageId": 1,
  "pages": 256,
  "publisherDate": "2019-04-11",
  "cover": "bit.ly/45BSyAI",
  "owner": 1
}

### Update information of the book

PUT localhost:8080/api/books/9
Content-Type: application/json

{
  "title": "REFACTOR Braiding Sweetgrass",
  "author": "REFACTOR Wall Kimmerer",
  "description": "REFACTOR Drawing on her life as an indigenous scientist, and as a woman, Kimmerer shows how other living beings...",
  "categoryId": 1,
  "languageId": 1,
  "pages": 4008,
  "publisherDate": "2015-04-11",
  "cover": "f:/book_db/1.jpg",
  "owner": 1
}

### Get all books without filter
GET localhost:8080/api/books/
Content-Type: application/json

### Get all books with filter - user_id
GET localhost:8080/api/books/?userId=5
Content-Type: application/json

### Get all books with filter - multiSearch
GET localhost:8080/api/books/?multiSearch=book
Content-Type: application/json


### Get all books with filter - categoryId
GET localhost:8080/api/books/?categoryId=2
Content-Type: application/json

### Get all books with filter - multi
GET localhost:8080/api/books/?languageId=1&userId=1&multiSearch=book
Content-Type: application/json

### Get all books with filter - language
GET localhost:8080/api/books/?languageId=1
Content-Type: application/json

### Get all books with filter -location
GET localhost:8080/api/books/?location=Berlin
Content-Type: application/json

### Get delail of book
GET localhost:8080/api/books/10/detail
Content-Type: application/json

### Add book to user
POST localhost:8080/api/books/getting
Content-Type: application/json

{
 "bookId": 1,
 "userId": 2
}

### Get my history
GET localhost:8080/api/books/history/1
Content-Type: application/json

### Get my waiting list
GET localhost:8080/api/books/waiting/1
Content-Type: application/json

### Get filter
GET localhost:8080/api/books/filter
Content-Type: application/json

### Get my list to send
GET localhost:8080/api/books/send/1
Content-Type: application/json

### Get info about next reader
GET localhost:8080/api/books/send/to
Content-Type: application/json

{
  "bookId": 3,
  "userId": 1
}

### Send book to next reader
POST localhost:8080/api/books/send/to
Content-Type: application/json

{
  "bookId": 3,
  "userId": 1
}

### Get info about all users book
GET localhost:8080/api/books/all/2
Content-Type: application/json

### Remove book from wait line
DELETE localhost:8080/api/books/remove
Content-Type: application/json

{
  "bookId": 2,
  "userId": 1
}