### Registration of user 1

POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "Qwerty007!"
}

### Login of user 1

POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=test1@gmail.com&password=Qwerty007!

### Logout of user 1

POST http://localhost:8080/logout