### Registration of user

POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "email": "alex2@gmail.com",
  "password": "Qwerty007!"
}

### Login of user

POST http://localhost:8080/api/login
Content-Type: application/x-www-form-urlencoded

username=alex2@gmail.com&password=Qwerty007!

### Logout

POST http://localhost:8080/api/logout

### Update user

PUT http://localhost:8080/api/users/54
Content-Type: application/json

{
  "newRole" : "USER",
  "newState" : "NOT_CONFIRMED",
  "firstName" : "Sam",
  "lastName" : "Smith",
  "postalCode" : "19394"
}