### Registration of user

POST http://localhost:8080/api/registration
Content-Type: application/json

{
  "email": "notcon@gmail.com",
  "password": "Qwerty007!"
}

### Login of user

POST http://localhost:8080/api/login
Content-Type: application/x-www-form-urlencoded

username=notcon@gmail.com&password=Qwerty007!

### Logout

POST http://localhost:8080/api/logout

### Update user
PUT http://localhost:8080/api/users/2
Content-Type: application/json

{
  "newRole" : "USER",
  "firstName" : "Sam",
  "lastName" : "Smith"
}

### Get my profile
GET http://localhost:8080/api/users/me
